name: online_groceries_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  adaptive_theme: ^3.6.0
  socket_io_client: ^3.0.2
  flutter_session_jwt: ^0.0.7
  dio: ^5.7.0
  fluttertoast: ^8.2.10
  iconify_flutter: ^0.0.5
  flutter_launcher_icons: ^0.14.2
  multi_select_flutter: ^4.1.3
  animated_custom_dropdown: ^3.1.1
  dropdown_search: ^6.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/
    - assets/location/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/Kantumruy-Pro-khmer-100-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-100-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-200-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-200-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-300-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-300-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-400-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-400-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-500-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-500-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-600-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-600-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-700-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-700-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-100-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-100-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-200-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-200-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-300-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-300-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-400-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-400-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-500-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-500-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-600-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-600-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-700-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-700-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-100-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-100-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-200-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-200-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-300-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-300-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-400-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-400-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-500-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-500-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-600-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-600-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-700-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-latin-ext-700-normal.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
